version: '3'

services:
  arabicmom-graphql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # GraphQL server
      - "8501:8501"  # Streamlit app
    environment:
      - FLASK_APP=app/graphql_server.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - GRAPHQL_SERVER_PORT=5001
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./data:/app/data
    restart: unless-stopped
